### ISSUE TITLE
README 이미지 추가 제안

### ISSUE THREAD

**Issue by PJunhyuk** [jessekim-ck/2020AIChallenge04#1]
![Screenshot from 2020-07-16 16-22-32](https://user-images.githubusercontent.com/11554157/88479631-8828cb00-cf8b-11ea-8405-340d8c495ea1.png)
README에 이 이미지 넣어주셔도 좋을 것 같아요ㅎㅎ 뭔가 풍성해보임..

**Comment by jessekim-ck** [comment]
ㅋㅋㅋ메이아이 URL과 함께 추가하였습니다 감사합니다!
